name: moodlet
description: Moodlet is a user-friendly mood tracker app designed to help you effortlessly log and visualize your daily emotions. Moodlet empowers you to understand and manage your emotional well-being with ease.
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


# ------------ PACKAGES ------------------- #

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8

  # Utilities
  logger: ^2.0.2+1
  connectivity_plus: ^5.0.2
  http: ^1.1.0
  intl: ^0.19.0
  url_launcher: ^6.1.14
  flutter_svg: ^2.0.9
  flutter_native_splash: ^2.3.10
  path: ^1.8.3

  # UI
  shimmer: ^3.0.0
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  animated_bottom_navigation_bar: ^1.3.1
  progressive_time_picker: ^0.0.9
  wheel_picker: ^0.0.4
  table_calendar: ^3.0.9
  animated_expandable_fab: ^0.0.3
  salomon_bottom_bar: ^3.3.2
  photo_view: ^0.14.0
  fl_chart: ^0.66.1
  animated_size_and_fade: ^4.0.0

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1

  # Database
  sqflite: ^2.3.2
  readmore: ^3.0.0
  touch_ripple_effect: ^2.4.0
  share_plus: ^9.0.0
  local_auth: ^2.2.0
  flutter_screen_lock: ^9.1.0
  awesome_notifications: ^0.8.2
  google_sign_in: ^6.2.1
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  firebase_storage: ^12.0.1
  path_provider: ^2.1.3
  image: ^4.2.0
  confetti: ^0.7.0
  tutorial_coach_mark: ^1.2.11
  flutter_expandable_fab: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/moodlet-logo.png"
  remove_alpha_ios: true

flutter:

  uses-material-design: true


  # ------------ IMAGES ------------------- #  

  assets:
    - assets/images/content/
    - assets/images/moods/
    - assets/images/moods/default/
    - assets/images/moods/simple/
    - assets/images/icons/png/
    - assets/images/icons/svg/
    - assets/images/emotions/
    - assets/images/activities/
    - assets/images/notification/
    - assets/logos/


  # ------------ FONTS ------------------- #

  fonts:
    - family: RedRose
      fonts:
        - asset: assets/fonts/RedRose-Light.ttf
          weight: 300
        - asset: assets/fonts/RedRose-Regular.ttf
          weight: 400
        - asset: assets/fonts/RedRose-Medium.ttf
          weight: 500
        - asset: assets/fonts/RedRose-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/RedRose-Bold.ttf
          weight: 800
          
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 800
          style: italic
