class QuoteModel {
  static List<String> quotes = [
    "The only way to do great work is to love what you do. - Steve Jobs",
    "In the middle of difficulty lies opportunity. - Albert Einstein",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "The best way to predict the future is to invent it. - Alan Kay",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "Quality is not an act, it is a habit. - Aristotle",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "The way to get started is to quit talking and begin doing. - Walt Disney",
    "You are enough just as you are. - Meghan Markle",
    "Dream big and dare to fail. - Norman Vaughan",
    "Act as if what you do makes a difference. It does. - William James",
    "The best way out is always through. - Robert Frost",
    "What we think, we become. - Buddha",
    "Stay hungry, stay foolish. - Steve Jobs",
    "You miss 100% of the shots you don’t take. - Wayne Gretzky",
    "Happiness is a warm puppy. - Charles M. Schulz",
    "Smile, it's free therapy. - Douglas Horton",
    "The best way to cheer yourself is to try to cheer someone else up. - Mark Twain",
    "A smile is a curve that sets everything straight. - Phyllis Diller",
    "Happiness is not by chance, but by choice. - Jim Rohn",
    "The best thing to hold onto in life is each other. - Audrey Hepburn",
    "Laughter is an instant vacation. - Milton Berle",
    "Do more of what makes you happy. - Unknown",
    "With the new day comes new strength and new thoughts. - Eleanor Roosevelt",
    "Every day is a second chance. - Unknown",
    "Start each day with a positive thought and a grateful heart. - Roy T. Bennett",
    "Every morning we are born again. What we do today is what matters most. - Buddha",
    "Make today so awesome yesterday gets jealous. - Unknown",
    "Today is the only day. Yesterday is gone. - John Wooden",
    "Be willing to be a beginner every single morning. - Meister Eckhart",
  ];
}
