// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO6OKsvci48ghEiQ3Hk7QrAUHQCt2lvZ8',
    appId: '1:31635925573:android:0aad628c68a2221a42112c',
    messagingSenderId: '31635925573',
    projectId: 'moodlet-79012',
    storageBucket: 'moodlet-79012.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6LlOXs6eAu8gduAPpxXehOFQbTCbNdYU',
    appId: '1:31635925573:ios:07816082751511c142112c',
    messagingSenderId: '31635925573',
    projectId: 'moodlet-79012',
    storageBucket: 'moodlet-79012.appspot.com',
    androidClientId: '31635925573-1savpmpbfs7tv1ppf8kbn7amq6llf7ri.apps.googleusercontent.com',
    iosClientId: '31635925573-p47n4kqnml96r8s329ugnqrds8t5cljt.apps.googleusercontent.com',
    iosBundleId: 'com.example.moodlet',
  );

}